import Foundation

// MARK: - Game content
// All hand-written, kid-level, and rooted in the stories the app tells.
// Keep additions unambiguous and gentle (no trick questions, no sting),
// and follow the copy rules in CLAUDE.md.

// MARK: Game stars (shared reward currency for the Games tab)

enum GameStars {
    static let key = "games.totalStars"

    /// Adds stars to the device-wide Games total (shown on the hub).
    static func award(_ count: Int) {
        guard count > 0 else { return }
        let defaults = UserDefaults.standard
        defaults.set(defaults.integer(forKey: key) + count, forKey: key)
    }
}

// MARK: Story Quiz

struct QuizQuestion {
    let prompt: String
    let choices: [String]
    let answerIndex: Int

    static let bank: [QuizQuestion] = [
        QuizQuestion(prompt: "Who built a big boat to keep the animals safe?",
                     choices: ["Noah", "Moses", "David"], answerIndex: 0),
        QuizQuestion(prompt: "What did God put in the sky as a promise to Noah?",
                     choices: ["A rainbow", "A cloud", "A kite"], answerIndex: 0),
        QuizQuestion(prompt: "How many of each animal walked onto Noah's boat?",
                     choices: ["Two", "Ten", "One"], answerIndex: 0),
        QuizQuestion(prompt: "Who was the shepherd boy who faced the giant Goliath?",
                     choices: ["Jonah", "David", "Peter"], answerIndex: 1),
        QuizQuestion(prompt: "What did David use to face Goliath?",
                     choices: ["A sword", "A sling and a stone", "A spear"], answerIndex: 1),
        QuizQuestion(prompt: "Before he was king, what was David's job?",
                     choices: ["Shepherd", "Fisherman", "Baker"], answerIndex: 0),
        QuizQuestion(prompt: "Where did Jonah end up when he ran from God?",
                     choices: ["In a big fish", "On a mountain", "In a castle"], answerIndex: 0),
        QuizQuestion(prompt: "How many days was Jonah inside the big fish?",
                     choices: ["Three", "Seven", "One"], answerIndex: 0),
        QuizQuestion(prompt: "Who spent a night with hungry lions and was kept safe?",
                     choices: ["Daniel", "Joseph", "Abraham"], answerIndex: 0),
        QuizQuestion(prompt: "Why was Daniel thrown to the lions?",
                     choices: ["He kept praying to God", "He lost a race", "He broke a pot"], answerIndex: 0),
        QuizQuestion(prompt: "What did Moses see burning that didn't burn up?",
                     choices: ["A bush", "A house", "A boat"], answerIndex: 0),
        QuizQuestion(prompt: "What happened to the sea when Moses lifted his staff?",
                     choices: ["It froze", "It split in two", "It turned gold"], answerIndex: 1),
        QuizQuestion(prompt: "Where did baby Moses float in his little basket?",
                     choices: ["The river", "The sea", "A pond in a garden"], answerIndex: 0),
        QuizQuestion(prompt: "Where was baby Jesus born?",
                     choices: ["A palace", "A stable", "A ship"], answerIndex: 1),
        QuizQuestion(prompt: "What led the wise men to baby Jesus?",
                     choices: ["A map", "A bright star", "A river"], answerIndex: 1),
        QuizQuestion(prompt: "Who visited the shepherds to tell them Jesus was born?",
                     choices: ["Angels", "Kings", "Sailors"], answerIndex: 0),
        QuizQuestion(prompt: "What did Jesus do to the stormy sea?",
                     choices: ["He told it to be still", "He swam in it", "He sailed away"], answerIndex: 0),
        QuizQuestion(prompt: "Where was Jesus sleeping when the storm began?",
                     choices: ["In the boat", "On the shore", "Up a tree"], answerIndex: 0),
        QuizQuestion(prompt: "How many loaves and fish fed the big crowd?",
                     choices: ["Five loaves and two fish", "Ten loaves", "A basket of apples"], answerIndex: 0),
        QuizQuestion(prompt: "What did the little boy share so Jesus could feed everyone?",
                     choices: ["His lunch", "His coat", "His sandals"], answerIndex: 0),
        QuizQuestion(prompt: "Who climbed a tree to see Jesus?",
                     choices: ["Zacchaeus", "Goliath", "Samuel"], answerIndex: 0),
        QuizQuestion(prompt: "What was Zacchaeus's job?",
                     choices: ["Tax collector", "Carpenter", "Shepherd"], answerIndex: 0),
        QuizQuestion(prompt: "In Jesus' story, who stopped to help the hurt traveler?",
                     choices: ["A king", "The good Samaritan", "A fisherman"], answerIndex: 1),
        QuizQuestion(prompt: "What does the shepherd do when one sheep is lost?",
                     choices: ["He goes looking for it", "He waits at home", "He buys a new one"], answerIndex: 0),
        QuizQuestion(prompt: "How many days did God take to make the world?",
                     choices: ["Six days, then He rested", "One day", "A hundred days"], answerIndex: 0),
        QuizQuestion(prompt: "What is the very first thing God said when making the world?",
                     choices: ["\"Let there be light\"", "\"Make a boat\"", "\"Count the stars\""], answerIndex: 0),
        QuizQuestion(prompt: "What fell down when Joshua's people marched and shouted?",
                     choices: ["The walls of Jericho", "A big tree", "The rain"], answerIndex: 0),
        QuizQuestion(prompt: "How many times did they march around Jericho on the last day?",
                     choices: ["Seven", "Two", "Twenty"], answerIndex: 0),
        QuizQuestion(prompt: "Whose colorful coat made his brothers jealous?",
                     choices: ["Joseph", "Daniel", "John"], answerIndex: 0),
        QuizQuestion(prompt: "Who gave Joseph his wonderful colorful coat?",
                     choices: ["His father", "A king", "His teacher"], answerIndex: 0),
        QuizQuestion(prompt: "Which brave queen spoke up to save her people?",
                     choices: ["Esther", "Mary", "Ruth"], answerIndex: 0),
        QuizQuestion(prompt: "What did God show Abraham to count?",
                     choices: ["The stars", "His sheep", "His coins"], answerIndex: 0),
        QuizQuestion(prompt: "Who walked on the water toward Jesus?",
                     choices: ["Peter", "Paul", "Pharaoh"], answerIndex: 0),
        QuizQuestion(prompt: "What was Peter's job before he followed Jesus?",
                     choices: ["Fisherman", "Soldier", "Farmer"], answerIndex: 0),
        QuizQuestion(prompt: "How did God speak to Elijah on the mountain?",
                     choices: ["In a gentle whisper", "With thunder only", "Through a lion"], answerIndex: 0),
        QuizQuestion(prompt: "What birds brought Elijah bread by the stream?",
                     choices: ["Ravens", "Doves", "Eagles"], answerIndex: 0),
        QuizQuestion(prompt: "In Jesus' story, what did the father do when his lost son came home?",
                     choices: ["Ran to hug him", "Closed the door", "Sent him away"], answerIndex: 0),
        QuizQuestion(prompt: "What did the wise man build his house on?",
                     choices: ["Rock", "Sand", "Snow"], answerIndex: 0),
        QuizQuestion(prompt: "What happened to the house built on sand?",
                     choices: ["It fell when the rain came", "It grew taller", "It floated away on a cloud"], answerIndex: 0),
        QuizQuestion(prompt: "Who was the boy who heard God calling his name at night?",
                     choices: ["Samuel", "Saul", "Simon"], answerIndex: 0),
        QuizQuestion(prompt: "Who said \"wherever you go, I will go\" and stayed with Naomi?",
                     choices: ["Ruth", "Esther", "Martha"], answerIndex: 0),
        QuizQuestion(prompt: "What did Jesus ride into Jerusalem while people waved branches?",
                     choices: ["A donkey", "A horse", "A camel"], answerIndex: 0),
        QuizQuestion(prompt: "How many friends did Jesus choose as His special helpers?",
                     choices: ["Twelve", "Three", "Fifty"], answerIndex: 0),
        QuizQuestion(prompt: "What did Jesus say about the little children?",
                     choices: ["\"Let them come to me\"", "\"They must wait outside\"", "\"They are too small\""], answerIndex: 0),
        QuizQuestion(prompt: "Who were the three friends kept safe in the fiery furnace?",
                     choices: ["Shadrach, Meshach and Abednego", "Peter, James and John", "Noah, Moses and David"], answerIndex: 0),
        QuizQuestion(prompt: "What did the woman find after sweeping her whole house?",
                     choices: ["Her lost coin", "A treasure map", "A little mouse"], answerIndex: 0),
        QuizQuestion(prompt: "What tiny seed did Jesus say grows into a big plant?",
                     choices: ["A mustard seed", "A pumpkin seed", "A sunflower seed"], answerIndex: 0),
        QuizQuestion(prompt: "Who helped Jesus' friends catch a huge net full of fish?",
                     choices: ["Jesus", "A sea captain", "Goliath"], answerIndex: 0),
        QuizQuestion(prompt: "What did Jesus heal for the man who couldn't see?",
                     choices: ["His eyes", "His ears", "His hands"], answerIndex: 0),
        QuizQuestion(prompt: "How many sheep did the shepherd have before one got lost?",
                     choices: ["One hundred", "Ten", "A thousand"], answerIndex: 0),
        QuizQuestion(prompt: "What did Mary and Joseph lay baby Jesus in?",
                     choices: ["A manger", "A golden bed", "A basket of flowers"], answerIndex: 0),
        QuizQuestion(prompt: "Who was swallowed up safe instead of sinking in the sea?",
                     choices: ["Jonah", "Joshua", "Jacob"], answerIndex: 0),
        QuizQuestion(prompt: "What did God make on the very last day of creation, before resting?",
                     choices: ["People", "The sun", "The fish"], answerIndex: 0),
        QuizQuestion(prompt: "Jesus said, \"I am the light of the...\"",
                     choices: ["world", "house", "garden"], answerIndex: 0),
        QuizQuestion(prompt: "What did the angel tell the women at Jesus' tomb?",
                     choices: ["\"He is risen!\"", "\"He is sleeping\"", "\"Come back later\""], answerIndex: 0),
        QuizQuestion(prompt: "Whose few little loaves became enough for thousands?",
                     choices: ["A boy who shared", "A rich king", "A baker"], answerIndex: 0),
        QuizQuestion(prompt: "What was Joseph (Mary's husband) good at building?",
                     choices: ["Things made of wood", "Stone castles", "Big ships"], answerIndex: 0),
        QuizQuestion(prompt: "When Jesus prayed in the garden, what did He ask God to happen?",
                     choices: ["God's will, not His own", "A big feast", "A new boat"], answerIndex: 0),
        QuizQuestion(prompt: "What do the birds and flowers teach us, according to Jesus?",
                     choices: ["God takes care of us", "How to fly", "How to cook"], answerIndex: 0),
        QuizQuestion(prompt: "Who got a brand-new name and became Paul?",
                     choices: ["Saul", "Simon", "Samson"], answerIndex: 0),
    ]
}

// MARK: Who Am I? (character riddles)

struct WhoAmIRiddle {
    let clues: [String]        // 3 clues, broad → specific
    let choices: [String]      // 3 names
    let answerIndex: Int

    static let bank: [WhoAmIRiddle] = [
        WhoAmIRiddle(clues: ["I worked with wood and hammers long before the rain came.",
                             "God told me to build something very, very big.",
                             "Animals came to me two by two!"],
                     choices: ["Noah", "Joseph", "Peter"], answerIndex: 0),
        WhoAmIRiddle(clues: ["I floated in a basket when I was a tiny baby.",
                             "I saw a bush that burned but didn't burn up.",
                             "I lifted my staff and the sea split in two!"],
                     choices: ["Jonah", "Moses", "David"], answerIndex: 1),
        WhoAmIRiddle(clues: ["I took care of sheep on the hillside.",
                             "I played the harp and wrote songs to God.",
                             "I faced a giant with just a sling and a stone!"],
                     choices: ["David", "Samuel", "Joshua"], answerIndex: 0),
        WhoAmIRiddle(clues: ["I prayed to God three times every day.",
                             "A king's rule couldn't stop my prayers.",
                             "I spent a whole night with hungry lions — and God kept me safe!"],
                     choices: ["Elijah", "Daniel", "Abraham"], answerIndex: 1),
        WhoAmIRiddle(clues: ["God asked me to go to a city, but I sailed the other way.",
                             "A big storm rocked my boat.",
                             "I spent three days inside a very big fish!"],
                     choices: ["Jonah", "Peter", "Noah"], answerIndex: 0),
        WhoAmIRiddle(clues: ["I became a queen in a faraway palace.",
                             "I was scared, but I went to see the king anyway.",
                             "My bravery saved my whole people!"],
                     choices: ["Ruth", "Mary", "Esther"], answerIndex: 2),
        WhoAmIRiddle(clues: ["My father gave me a very special present.",
                             "My brothers were jealous of my colorful coat.",
                             "Years later, I forgave them and shared my food!"],
                     choices: ["Joseph", "David", "Samuel"], answerIndex: 0),
        WhoAmIRiddle(clues: ["An angel brought me amazing news.",
                             "I sang a happy song to God about it.",
                             "I laid my baby boy in a manger in Bethlehem!"],
                     choices: ["Ruth", "Mary", "Esther"], answerIndex: 1),
        WhoAmIRiddle(clues: ["I was a fisherman before I met Jesus.",
                             "I once stepped out of a boat onto the waves.",
                             "I walked on water toward Jesus!"],
                     choices: ["Peter", "Paul", "John"], answerIndex: 0),
        WhoAmIRiddle(clues: ["I was short — too short to see over the crowd.",
                             "So I climbed up a sycamore tree.",
                             "Jesus came to MY house for dinner!"],
                     choices: ["Zacchaeus", "Samuel", "Timothy"], answerIndex: 0),
        WhoAmIRiddle(clues: ["God asked me to move to a brand-new land.",
                             "God told me to count the stars in the sky.",
                             "God promised my family would be that big!"],
                     choices: ["Abraham", "Noah", "Jacob"], answerIndex: 0),
        WhoAmIRiddle(clues: ["I would not leave Naomi alone.",
                             "I said, \"Wherever you go, I will go.\"",
                             "I gathered grain in the fields to care for us both!"],
                     choices: ["Esther", "Ruth", "Martha"], answerIndex: 1),
        WhoAmIRiddle(clues: ["I was just a boy helping in God's house.",
                             "One night I heard someone call my name.",
                             "It was God calling — and I said, \"Speak, I'm listening!\""],
                     choices: ["Samuel", "David", "Daniel"], answerIndex: 0),
        WhoAmIRiddle(clues: ["Ravens brought me bread by a little stream.",
                             "I raced a rainstorm down a mountain.",
                             "God spoke to me in a gentle whisper!"],
                     choices: ["Elisha", "Elijah", "Moses"], answerIndex: 1),
        WhoAmIRiddle(clues: ["I led God's people after Moses.",
                             "I wasn't afraid of big city walls.",
                             "We marched around Jericho and the walls fell down!"],
                     choices: ["Joshua", "Gideon", "Caleb"], answerIndex: 0),
        WhoAmIRiddle(clues: ["I'm not a person — I twinkled high in the night sky.",
                             "Wise men followed me a long, long way.",
                             "I stopped right over the place where baby Jesus lay!"],
                     choices: ["The bright star", "The moon", "A firefly"], answerIndex: 0),
    ]
}

// MARK: True or Lumi? (true/false)

struct TrueFalseItem {
    let statement: String
    let isTrue: Bool
    /// One gentle line shown after answering.
    let note: String

    static let bank: [TrueFalseItem] = [
        TrueFalseItem(statement: "Noah's boat was full of animals, two by two.", isTrue: true,
                      note: "Yes! God kept every one of them safe."),
        TrueFalseItem(statement: "Goliath won the battle against David.", isTrue: false,
                      note: "David won — with one little stone and a big trust in God."),
        TrueFalseItem(statement: "Jonah rode to Nineveh on a camel.", isTrue: false,
                      note: "A big fish carried Jonah — then he went to Nineveh."),
        TrueFalseItem(statement: "Daniel was kept safe in the lions' den.", isTrue: true,
                      note: "God sent an angel to shut the lions' mouths."),
        TrueFalseItem(statement: "Baby Jesus was born in a fancy palace.", isTrue: false,
                      note: "He was born in a humble stable and laid in a manger."),
        TrueFalseItem(statement: "Jesus calmed a storm with just His words.", isTrue: true,
                      note: "\"Peace, be still!\" — and the sea got quiet."),
        TrueFalseItem(statement: "Moses crossed the sea on a wooden bridge.", isTrue: false,
                      note: "God split the sea so everyone walked through on dry ground!"),
        TrueFalseItem(statement: "Zacchaeus climbed a tree to see Jesus.", isTrue: true,
                      note: "He was too short for the crowd — so up he went!"),
        TrueFalseItem(statement: "The walls of Jericho fell after the people marched and shouted.", isTrue: true,
                      note: "Seven times around on the last day — then down they came."),
        TrueFalseItem(statement: "Joseph's special coat was plain and gray.", isTrue: false,
                      note: "It was wonderfully colorful — that's why his brothers were jealous."),
        TrueFalseItem(statement: "God made the world in six days and rested on the seventh.", isTrue: true,
                      note: "And He saw that it was very good."),
        TrueFalseItem(statement: "Jesus fed thousands of people with five loaves and two fish.", isTrue: true,
                      note: "A little lunch, shared, became more than enough."),
        TrueFalseItem(statement: "The lost sheep had to find its own way home.", isTrue: false,
                      note: "The shepherd went looking until he found it — just like God looks after us."),
        TrueFalseItem(statement: "Esther was too scared to talk to the king.", isTrue: false,
                      note: "She WAS scared — but she went anyway. That's what brave means."),
        TrueFalseItem(statement: "Peter walked on water toward Jesus.", isTrue: true,
                      note: "And when he wobbled, Jesus caught him right away."),
        TrueFalseItem(statement: "An angel told the shepherds about baby Jesus.", isTrue: true,
                      note: "Good news of great joy — for everyone!"),
        TrueFalseItem(statement: "The wise men followed a rainbow to find Jesus.", isTrue: false,
                      note: "They followed a bright star all the way to Bethlehem."),
        TrueFalseItem(statement: "The wise man built his house on the sand.", isTrue: false,
                      note: "On the rock! The sand house fell when the rain came."),
        TrueFalseItem(statement: "God spoke to Elijah in a gentle whisper.", isTrue: true,
                      note: "Not the wind, not the fire — a quiet little whisper."),
        TrueFalseItem(statement: "Ruth left Naomi all alone.", isTrue: false,
                      note: "Ruth stayed. \"Wherever you go, I will go.\""),
        TrueFalseItem(statement: "Samuel heard God calling his name at night.", isTrue: true,
                      note: "And he answered, \"Speak, I'm listening!\""),
        TrueFalseItem(statement: "The prodigal son's father slammed the door on him.", isTrue: false,
                      note: "His father RAN to hug him. God welcomes us home like that."),
        TrueFalseItem(statement: "Jesus rode into Jerusalem on a donkey.", isTrue: true,
                      note: "While the people waved branches and cheered!"),
        TrueFalseItem(statement: "Jesus told the little children to go away.", isTrue: false,
                      note: "He said, \"Let the little children come to me.\""),
        TrueFalseItem(statement: "Shadrach, Meshach and Abednego were kept safe in the fire.", isTrue: true,
                      note: "God was right there in the furnace with them."),
        TrueFalseItem(statement: "Baby Moses floated in a little basket on the river.", isTrue: true,
                      note: "His sister Miriam watched over him the whole time."),
        TrueFalseItem(statement: "A mustard seed is the biggest seed in the world.", isTrue: false,
                      note: "It's one of the tiniest — but it grows into something big and wonderful."),
        TrueFalseItem(statement: "The angel at the tomb said, \"He is risen!\"", isTrue: true,
                      note: "The happiest morning there ever was."),
    ]
}

// MARK: Story Scramble (put the story in order)

struct ScrambleStory {
    let title: String
    let steps: [String]   // 4 steps in correct order

    static let bank: [ScrambleStory] = [
        ScrambleStory(title: "Noah's Big Boat",
                      steps: ["God tells Noah to build a big boat",
                              "The animals come in two by two",
                              "It rains and rains and rains",
                              "A rainbow shines — God's promise!"]),
        ScrambleStory(title: "David and Goliath",
                      steps: ["Goliath shouts and everyone is afraid",
                              "Little David says \"I'll go!\"",
                              "David swings his sling with one stone",
                              "The giant falls — God gave courage!"]),
        ScrambleStory(title: "Jonah and the Big Fish",
                      steps: ["God says \"Go to Nineveh\" — Jonah sails away instead",
                              "A storm rocks the boat",
                              "A big fish swallows Jonah safely",
                              "Jonah says sorry and goes to Nineveh"]),
        ScrambleStory(title: "The Birth of Jesus",
                      steps: ["Mary and Joseph travel to Bethlehem",
                              "There's no room, so they stay in a stable",
                              "Baby Jesus is born and laid in a manger",
                              "Shepherds and wise men come to see Him"]),
        ScrambleStory(title: "Daniel and the Lions",
                      steps: ["Daniel prays to God every day",
                              "The king's law says \"no praying!\"",
                              "Daniel is put in the lions' den",
                              "God shuts the lions' mouths — Daniel is safe!"]),
        ScrambleStory(title: "The Walls of Water",
                      steps: ["God's people reach the big sea",
                              "Moses lifts his staff high",
                              "The sea splits into two tall walls",
                              "Everyone walks through on dry ground"]),
        ScrambleStory(title: "Feeding the Five Thousand",
                      steps: ["A huge crowd gets hungry",
                              "A boy shares his five loaves and two fish",
                              "Jesus gives thanks and breaks the bread",
                              "Everyone eats — with baskets left over!"]),
        ScrambleStory(title: "Joshua and Jericho",
                      steps: ["Joshua's people reach the giant walls",
                              "They march around the city each day",
                              "On day seven they march and SHOUT",
                              "The walls come tumbling down"]),
        ScrambleStory(title: "Zacchaeus",
                      steps: ["Zacchaeus is too short to see Jesus",
                              "He climbs a sycamore tree",
                              "Jesus says \"I'm coming to your house!\"",
                              "Zacchaeus shares and his heart is changed"]),
        ScrambleStory(title: "The Creation Story",
                      steps: ["God says \"Let there be light\"",
                              "God makes the sky, land and seas",
                              "God fills the world with plants and animals",
                              "God makes people, then rests and smiles"]),
    ]
}
